<template>
    <div>
        Colaboradores
        Colaboradores
        Colaboradores
        Colaboradores
        Colaboradores
        Colaboradores
        Colaboradores
        Colaboradores
        Colaboradores
        Colaboradores
    </div>
</template>